name = "easytakt"
compatibility_date = "2024-03-27"
main = "workers-site/index.js"

[site]
bucket = "out"

# Custom domain configuration
routes = [
  { pattern = "www.easytakt.com", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker" 