import { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy - EasyTakt',
  description: 'Privacy policy and data protection information for EasyTakt users.',
};

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-gradient-to-b from-gray-50 to-white pt-32">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
          <div className="prose prose-lg max-w-none">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
            <p className="text-gray-500 mb-8">Last updated: April 03, 2025</p>
            
            <div className="space-y-12">
              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <p className="text-gray-600">
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p className="text-gray-600 mt-4">
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Interpretation and Definitions</h2>
                <h3 className="text-xl font-medium text-gray-900 mb-3">Interpretation</h3>
                <p className="text-gray-600 mb-6">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. 
                  The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                
                <h3 className="text-xl font-medium text-gray-900 mb-3">Definitions</h3>
                <p className="text-gray-600 mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-3 text-gray-600">
                  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong>Application</strong> refers to EasyTakt, the software program provided by the Company.</li>
                  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to 64Bit Labs, UG, Kolonnenstr. 8, 10827 Berlin.</li>
                  <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li><strong>Country</strong> refers to: Berlin, Germany</li>
                  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service</strong> refers to the Application or the Website or both.</li>
                  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><strong>Website</strong> refers to EasyTakt, accessible from https//app.easytakt.com</li>
                  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Collecting and Using Your Personal Data</h2>
                <h3 className="text-xl font-medium text-gray-900 mb-3">Types of Data Collected</h3>
                
                <h4 className="text-lg font-medium text-gray-900 mb-2">Personal Data</h4>
                <p className="text-gray-600 mb-4">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. 
                  Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600 mb-6">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>

                <h4 className="text-lg font-medium text-gray-900 mb-2">Usage Data</h4>
                <p className="text-gray-600 mb-4">Usage Data is collected automatically when using the Service.</p>
                <p className="text-gray-600 mb-4">
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, 
                  the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers 
                  and other diagnostic data.
                </p>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Tracking Technologies and Cookies</h2>
                <p className="text-gray-600 mb-4">
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. 
                  The technologies We use may include:
                </p>
                <ul className="list-disc pl-6 space-y-3 text-gray-600">
                  <li>
                    <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all 
                    Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
                  </li>
                  <li>
                    <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit 
                    the Company to count users who have visited those pages or opened an email and for other related website statistics.
                  </li>
                </ul>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Use of Your Personal Data</h2>
                <p className="text-gray-600 mb-4">The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-3 text-gray-600">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account and registration as a user of the Service.</li>
                  <li>For the performance of a contract and service delivery.</li>
                  <li>To contact You regarding updates or informative communications about the Service.</li>
                  <li>To provide You with news, special offers and general information about our services.</li>
                  <li>To manage Your requests and provide customer support.</li>
                  <li>For business transfers, evaluations, and organizational changes.</li>
                  <li>For data analysis, identifying usage trends, and improving our Service.</li>
                </ul>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Security of Your Personal Data</h2>
                <p className="text-gray-600">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, 
                  or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your 
                  Personal Data, We cannot guarantee its absolute security.
                </p>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Changes to this Privacy Policy</h2>
                <p className="text-gray-600 mb-4">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className="text-gray-600">
                  We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update 
                  the "Last updated" date at the top of this Privacy Policy.
                </p>
              </div>

              <div className="bg-white rounded-2xl p-8 shadow-sm">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
                <p className="text-gray-600 mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>By email: <a href="mailto:privacy@easytakt.com" className="text-blue-600 hover:text-blue-700">privacy@easytakt.com</a></li>
                  <li>By visiting our <Link href="/contact" className="text-blue-600 hover:text-blue-700">contact page</Link></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
} 